name: Test PR
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0 # Use 7.5.0 like other Saleor packages, to avoid pnpm version conflicts.
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check linters
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build

  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OSV
        run: curl -skL https://github.com/google/osv-scanner/releases/download/v1.0.1/osv-scanner_1.0.1_linux_amd64 > osv-scanner
      - name: chmod 
        run: chmod a+x osv-scanner 
      - name: Check for vulnerabilities 
        run: ./osv-scanner -L pnpm-lock.yaml --json | jq -e '.results | length == 0'
