name: Release on GitHub & Publish to NPM
on: 
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Which version to release?
        options: 
          - major 
          - minor 
          - patch
          - preminor
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install the dependencies
        run: pnpm install
      - name: Setup the NPM Registry
        run: pnpm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release for `@saleor/cli`
        run: pnpm release ${{ inputs.version }} --ci ${{ startsWith(inputs.version, 'pre') && '--preRelease=rc --npm.tag=next' || '' }} --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: node -e "let pkg=require('./package.json'); pkg.name='saleor'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
      - name: Release for `saleor`
        run: pnpm release ${{ inputs.version }} --ci ${{ startsWith(inputs.version, 'pre') && '--preRelease=rc --npm.tag=next' || '' }} --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: node -e "let pkg=require('./package.json'); pkg.name='saleor-cli'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
      - name: Release for `saleor-cli`
        run: pnpm release ${{ inputs.version }} --ci ${{ startsWith(inputs.version, 'pre') && '--preRelease=rc --npm.tag=next' || '' }} --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: node -e "let pkg=require('./package.json'); pkg.name='@saleor/cli'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

