name: Execute nightly tests

on:
  schedule:
    - cron: '0 6 * * 1-5'

  repository_dispatch:
    types: [automation-tests-event]

jobs:
  run-functional-tests:
    if: ${{ github.event_name != 'repository_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.5.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Prepare saleor CLI
        run: pnpm build

      - name: Write config file
        id: write-config-file
        env:
          CLI_ACCESS_TOKEN: ${{ secrets.CLI_ACCESS_TOKEN }}
          CLI_GITHUB_TOKEN: ${{ secrets.CLI_GITHUB_TOKEN }}
          CLI_VERCEL_TOKEN: ${{ secrets.CLI_VERCEL_TOKEN }}
          TEST_COMMAND: 'node dist/saleor.js'
        run: echo '{"token":"${{ secrets.CLI_ACCESS_TOKEN }}","telemetry":"false", "github_token":"${{ secrets.CLI_GITHUB_TOKEN }}", "vercel_token":"${{ secrets.CLI_VERCEL_TOKEN }}"  }' > ~/.config/saleor.json

      - name: pre run
        env:
          SALEOR_CLI_ENV: staging
          RUN_FUNCTIONAL_TESTS: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node dist/saleor.js info
          node dist/saleor.js status

      - name: run tests
        env:
          SALEOR_CLI_ENV: staging
          RUN_FUNCTIONAL_TESTS: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'GA-saleor-cli'
          git config --global user.email 'GA-saleor-cli@users.noreply.github.com'
          pnpm test-functional

      - name: Notify Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SNAP_RESTORE }}
          SLACK_USERNAME: FunctionalTestsBot
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Functional tests failed"
          SLACK_MESSAGE: "https://github.com/saleor/saleor-cli/actions/workflows/tests-nightly.yml"
          MSG_MINIMAL: true